version: '3.8'
services:
  hackathon-module:
    build: .
    networks:
      - cpp-edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hackathon-module.rule=PathPrefix(`/test/hackathon-module`)"
      - "traefik.http.routers.hackathon-module.entrypoints=websecure"
      - "traefik.http.routers.hackathon-module.tls.certresolver=letsencrypt"
      - "traefik.http.services.hackathon-module.loadbalancer.server.port=3000"

networks:
  cpp-edge:
    external: true
